######################################################################
# Automatically generated by qmake (3.0) Tue Dec 31 12:59:39 2013
######################################################################

TEMPLATE = app
TARGET = MPIBrot
INCLUDEPATH += .
CONFIG += x86_64

# Input
HEADERS += Mandelbrot.h ui_mainwindow.h MainWindow.h DisplayArea.h
SOURCES += main.cpp Mandelbrot.cpp MainWindow.cpp DisplayArea.cpp
FORMS += MainWindow.ui
